baseURL = 'https://gianortiz.com/'
languageCode = 'en-us'
title = 'Gian Ortiz'
theme = 'not-much'
showPostsSummary = true

[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "posts"
  name = "posts"
  title = "Posts"
  url = "/posts"
  weight = 2

[[menu.main]]
  identifier = "github"
  name = "github"
  title = "GitHub"
  url = "https://github.com/GianOrtiz"
  weight = 3

[params]
  theme = "dark"
  pallete = "dracula"

[caches]
  [caches.images]
    dir = ':cacheDir/images'